### PR TITLE
Issue #117 - Changing token

### PR DESCRIPTION
**Pull request by pecko**

### CODE REVIEW

**Comment by IanMayo** [comment]
are you able to tell if this will work? Or will we only know once it's merged?

**Comment by pecko** [comment]
It will be skipped in PR. We have to merge to test. I have also added maven cache. It should be speed up a build.

**Comment by pecko** [comment]
> I have also added maven cache. It should be speed up a build.

We should probably add it to debrief too.

**Comment by IanMayo** [comment]
sure - please create a Debrief PR, to compare the performance before/after

On 7 December 2015 at 17:06, Haris Peco notifications@github.com wrote:

> I have also added maven cache. It should be speed up a build.
> 
> We should probably add it to debrief too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/debrief/limpet/pull/162#issuecomment-162594426.

## 

Ian Mayo
Deep Blue C Technology Ltd
- New technologies, implemented well

**Comment by pecko** [comment]
I have created https://github.com/debrief/debrief/issues/1395. Will solve it after testing the feature in limpet.

**Comment by pecko** [comment]
Travis is much slower now and the build fails. I think that our caching doesn't cause it. I have restarted it.

**Comment by pecko** [comment]
Travis is slower to start build too. It is some issue (or high load) on travis.

**Comment by IanMayo** [comment]
ok, should I merge? Or wait until we understand more?

**Comment by pecko** [comment]
The build passes now. Restarting to test cache.

**Comment by pecko** [comment]
> ok, should I merge? Or wait until we understand more?

Please wait to finish a new build.

**Comment by pecko** [comment]
Cache work. Now the limpet build is much faster. See https://travis-ci.org/debrief/limpet/pull_requests.
You can merge.

**Pull request merged**
