### PR TITLE
added org.freehep and support export to wmf format on stack charts

### PR DESCRIPTION
**Pull request by theanuradha**
image

image

### CODE REVIEW

**Comment by IanMayo** [comment]
Great, well done.  Could you also investigate copy/paste via the Clipboard?

**Comment by theanuradha** [comment]
@IanMayo  I tested on windows 
and this is what it export 

image

from 

image

**Comment by theanuradha** [comment]
you mean copy to Clipboard than export to file ?

**Comment by IanMayo** [comment]
No, put the metafile image onto the clipboard, so it can then be pasted into MS Word.

**Comment by theanuradha** [comment]
OK I will have a go

**Comment by theanuradha** [comment]
@IanMayo I have added Clipboard support but I do not have verification to see it can be pasted (eg ms- word ) correctly. can you try this  ?

**Comment by IanMayo** [comment]
Can't you try to paste it into another application (keynote, pages on osx, WordPad on Win)

**Comment by theanuradha** [comment]
I did not found app that support on osx will try WordPad

**Comment by theanuradha** [comment]
@IanMayo  Paste is not working yet as Im trying to port it to SWT Clipboard

**Comment by theanuradha** [comment]
@IanMayo OK Now works. I have gave up on SWT Clipboard and switch to AWT version. In this case it is safe to use AWT version. 

It works perfectly in Wordpad

**Comment by theanuradha** [comment]
image

**Comment by IanMayo** [comment]
Hmm, shouldn't this work on OSX?  I tried pasting to MS Word, but there was nothing on the clipboard.

**Comment by theanuradha** [comment]
@IanMayo it dose copy to clipboard but seems on osx MS-word not support the format

**Comment by theanuradha** [comment]
http://answers.microsoft.com/en-us/mac/forum/macoffice2011-macword/paste-special-picture-enhanced-metafile/99c940f7-aa64-46f0-811d-60221be5682e?auth=1

**Comment by IanMayo** [comment]
Ok, could you try to make a platform-specific change?

For Windows, continue to use EMFGraphics2D

For OSX & Linux, could you use PDFGraphics2D?

I'm pretty sure you'll need to change the transfer mime type.

Actually, it would be good to wrap the two behaviours into their own class.  Then we can allow the choice of both exports on Windows platforms.

thanks :-)

**Pull request merged**
