### PR TITLE
new version of nebula

### PR DESCRIPTION
**Pull request by theanuradha**
This version works perfect on osx and no more flick

### CODE REVIEW

**Comment by IanMayo** [comment]
Hi there @theanuradha - Rodrigo has managed to fix the outstanding Linux flicker issue.  He left this note:

# 

I updated the https://github.com/cantupolo/nebula/tree/stw-linuxmacosx-fixes branch with the changes. Most of the changes are on the application that uses the nebula code, so you have to update your application accordingly. Please check the TransitionTest1 class changes in the demo application to verify what needs to be done in your application.

Other note: I don't know if you guys know about this but, on Linux, I verified that the demo application runs much better if you disable GTK3 on SWT. To do this, please set the SWT_GTK3 environment variable to 0.

# 

I haven't tried the GTK3 fix.

**Comment by theanuradha** [comment]
@IanMayo  new version added and ported fix to our code

**Comment by IanMayo** [comment]
I'm getting strange bug:

```
java.lang.ArrayIndexOutOfBoundsException: 2
    at info.limpet.stackedcharts.ui.view.StackedChartsView$3.getControlImage(StackedChartsView.java:289)
    at org.eclipse.nebula.effects.stw.TransitionManager.hasImageToGetFromControl(TransitionManager.java:329)
    at org.eclipse.nebula.effects.stw.TransitionManager.startTransition(TransitionManager.java:187)
    at org.eclipse.nebula.effects.stw.TransitionManager$1.widgetSelected(TransitionManager.java:77)
    at info.limpet.stackedcharts.ui.view.StackedPane.fireSelection(StackedPane.java:168)
    at info.limpet.stackedcharts.ui.view.StackedPane.showPane(StackedPane.java:91)
    at info.limpet.stackedcharts.ui.view.StackedPane.showPane(StackedPane.java:76)
    at info.limpet.stackedcharts.ui.view.StackedChartsView.selectView(StackedChartsView.java:517)
    at info.limpet.stackedcharts.ui.view.StackedChartsView$6.run(StackedChartsView.java:380)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:452)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3562)
```

Our array is two elements long, but we try to set/retrieve the image in position **2**.  So, if I subtract one from the image index, then the Linux transitions work perfectly.

Since this particular code is Linux specific, my change shouldn't affect Win/OSX.  But, could you double-check please @theanuradha  ?

**Comment by theanuradha** [comment]
@IanMayo Sure

**Comment by theanuradha** [comment]
@IanMayo  Looks correct

**Pull request merged**
