### PR TITLE
Issue #217 - Refactor DataManagerEditor actions to standalone classes

### PR DESCRIPTION
**Pull request by pecko**

### CODE REVIEW

**Comment by IanMayo** [comment]
thanks for this.

unfortunately, I don't want these commands to sit in the RCP namespace.  I wish them to site in the info.limpet namespace - so they can be more easily tested, and potentially used in non-RCP applications.  Interaction with the UI should be from the calling class (DataManagerEditor will call getSuitableObjects() and pass them in), or from the IContext object.

If this seems to complex then I can refactor it when I get back to work next week.

(happy new year :-) )

**Comment by pecko** [comment]
@IanMayo 
I'm misunderstood you want separate actions only from DataManagerEditor. I think I understand now that you want separate it from UI completely and even move to info.limpet plugin. IMO, it is doable using UIContext that will be UI agnostic.
I will try it asap.

> (happy new year :-) )

Happy new year to you too :)

**Comment by pecko** [comment]
@IanMayo 

I have moved the actions to the info.limpet plugin/namespace. Commit: https://github.com/debrief/limpet/commit/f731cae30e9ddcd69c4f900485dbf2c54be36178

Notice:
1) Current implementation adds org.eclipse.jface (requires org.eclipse.swt) to the info.limpet plugin. I suppose that you don't want that (maybe a user want to implement the actions in Swing). I will try to remove these dependencies tomorrow.
2) I have to create IGroupWrapper interface, since some actions use GroupWrapper which is defined in info.limpet.rcp. I hope that it's acceptable.

Also, I have to test the actions slightly. This is just for you to review.

**Comment by pecko** [comment]
> 1) Current implementation adds org.eclipse.jface (requires org.eclipse.swt) to the info.limpet plugin. 
> I suppose that you don't want that (maybe a user want to implement the actions in Swing). I will try to 
> remove these dependencies tomorrow.

I have tried to remove the org.eclipse.jface dependencies. However, main action class (Action) is defined in the org.eclipse.jface plugin so removing this dependencies would be to create jface action again in the info.limpet.rcp plugin.
Maybe, we could create own actions (operations) that could be imlemented with JFace/RCP as well as some other framework

@IanMayo 

Please advice what we should do.

**Comment by IanMayo** [comment]
Yes, Action is in the JFace namespace.

We can avoid depending on Action by making these operations extend IOperation and ICommand (see the existing **AddLayerOperation**).  

I can see that for CsvToClipboard we'll have to add a **placeOnClipboard(String txt)** command to the IContext object.

So, I guess in our RCP data manager, we'll wrap these IOperation objects in an RCP Action. Then when clicked, we get the selection, pass it to **csvToClipboard.actionsFor()**.  If an ICommand is returned, we'll execute it.

I hope this makes sense.

**Comment by pecko** [comment]
Yes, it makes sense. I just want to know if you want to remove the org.eclipse.jface/swt dependencies.
Will fix it asap.

**Comment by IanMayo** [comment]
@pecko - yes, please remove JFace/SWT dependencies from info.limpet.

**Pull request merged**
