### PR TITLE
stacked charts - EMF model prototype

### PR DESCRIPTION
**Pull request by dinkoivanov**
Two plugins added:
- info.limpet.stackedcharts.model
- info.limpet.stackedcharts.model.test

The model artifacts are located in the model folder of the first plugin. Those are:
- stackedcharts.ecore
- stackedcharts.ecore_diagram
- stackedcharts.genmodel

The .ecore file contains the metamodel definiton. It can be edited with a tree editor like this:
capture
For better user experience, you can use the .ecore_diagram file. It's building an UML-like diagram on top of the ecore file. Any change to the .ecore_diagram file is reflected in the .ecore file as well. To use that however you'll need to install the "Graphical Modeling Framework Tooling" component. For that you can use the Help > Install Modeling components:
capture1
...or Help > Eclipse Marketplace.

The .genmodel file is a Generator Model. It contains metadata describing the code generation process, such as what Java package, what plugin, etc.

The usual workflow is like that:
1. Edit the ecore diagram
2. Reload the genmodel file (Right click > Reload > Next > Click "Load" > Next > Finish)
3. Generate code from the genmodel (Open the genmodel file > Right Click the root nodel > Generate Model Code)

The info.limpet.stackedcharts.model.tests plugin contains a JUnit test that should give you an impression of how the EMF model is manipulated.

In addition, the target platform definition was updated to include the EMF feature:
capture2

### CODE REVIEW

**Comment by IanMayo** [comment]
Hi there, up & running!

Two queries:
1) when I generated code, it changed quite a lot of existing java source files, and created some new ones. Maybe this is related to us using different versions of GMF, or EMF Diagram editor
2) I'd like to be able to add text to the diagram that gets included as Java code comments.  I only have the editable properties as shown below:
ecoreeditor

Can you give me any tips?

[no rush at all on this..]

**Comment by dinkoivanov** [comment]
Regarding 1) - it might be normal I think, depends on the changes. For example if you just move around an element in the diagram and regenerate, that should not change anything.
About 2) - here's a way to do it: http://www.vogella.com/tutorials/EclipseEMF/article.html#javadoc
Select the element and enter the documentation under Annotation > GenModel Doc property.

**Comment by IanMayo** [comment]
Yes, @dinkoivanov - I saw  that article. But, as my screenshot shows, I just don't have those tabs in my properties view.  I just have "core" and "appearance".

I've switched to Mars, & then Neon M6.  I think I'm missing something.  In Vogella's screenshots the diagram entities are colored, in mine they're not.  I followed the steps in his tutorial, and got a suitable (color) diagram editor. But, after I close & re-open, I don't see it. Hmm, learning curve...

Would you mind attaching a screenshot of what your stacked charts diagram editor looks like?

**Comment by IanMayo** [comment]
Duh, I see from the UpWork screenshot that you don't have the **Annotation** page in your properties view:
dinko_ui

So, there's another reason why I'm not able to add class/method comments.

I wonder if there are different versions of ecore model?

**Comment by dinkoivanov** [comment]
Hi Ian,
Indeed we were using the diagramming editor that comes with GMF which appears to be simpler. The one that Lars is using in his tutorial is a better one I guess. With the last push, I've migrated our project to make use of it. You'll need to install EcoreTools (from Help > Install Modeling Components menu).
capture
Workflow there is a bit different, you need to go to the modeling perspective, expand the model.aird node and double click the "model" node to open the editor:
capture1
As you can see the properties view contains the additional annotations.

**Pull request merged**
