### PR TITLE
Hotfix test release

### PR DESCRIPTION
**Pull request by IanMayo**
Minor update, to test release/P2 process

### CODE REVIEW

**Comment by IanMayo** [comment]
@pecko  - I'm experimenting with producing an updated release.  It looks like I've got something wrong.  Can you see the problem?

**Comment by pecko** [comment]
Checking...

**Comment by pecko** [comment]
Could I rebase this branch? It will include the latest commit from issue #125

**Comment by IanMayo** [comment]
sure, yes.

**Comment by pecko** [comment]
I have created the branch in my fork and will create a new PR

**Comment by pecko** [comment]
It works now. See commit https://github.com/debrief/limpet/commit/41e85a8a1192effd9c05688f232358a7454e5f97
It have to be applied in order to test update site.

**Pull request merged**
