### PR TITLE
Workaround for JRE 1.7 code to compiler without errors under JRE 1.8

### LINKED ISSUE #409: Jre 1.7 compiler warning
I've just opened Limpet on a fresh Windows 10 PC.   I'm running Eclipse 3.8.2, with a single JRE installed (1.8.0_111).

There were lots of compiler warnings, until I changed the **Compiler compliance level** from 1.4 to 1.7.

But, I still have 3 errors:
image

The issue may be described here:
http://stackoverflow.com/a/26481337/92441

I'd appreciate you:
a) trying to reproduce the errors
b) making code changes necessary to avoid the errors

I remember that I've fixed it in the past by installing JRE 1.7 and using that. But, a source code fix would be a neater improvement.

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #409

### CODE REVIEW

**Comment by IanMayo** [comment]
@theanuradha - does this seem a valid fix for #409 ?  See any problems?

**Comment by IanMayo** [comment]
@theanuradha  - no, it's failing.  spliterator was only introduced with 1.8.

Hmm, suggestions welcome.  Otherwise  I guess I'll have to install a JRE 1.7.

**Comment by theanuradha** [comment]
let me have go on this

**Comment by IanMayo** [comment]
Drop it, it doesn't fix it,

**Pull request closed without merging**
