### PR TITLE
Issue 1809 export png

### PR DESCRIPTION
**Pull request by theanuradha**
Added Export to PNG and set on Clipboard.
 (I Had tried on SVG but none of apps allow SVG paste to test it)

### CODE REVIEW

**Comment by theanuradha** [comment]
@IanMayo Not sure you want to export to png but I went ahead and added. 

SVG export on separate branch on my repo https://github.com/theanuradha/limpet/tree/issue_1809_export_svg

**Comment by IanMayo** [comment]
@theanuradha - did you try PDF export?

https://github.com/debrief/debrief/issues/1809#issuecomment-235887036

A pasted PDF image is a vector, so the lines stay crisp.

(but export to PNG is still welcome, thanks :-) )

**Comment by theanuradha** [comment]
@IanMayo I tried   PDFGraphics2D but it is not possible to paste the PDF byte-stream  to another application .(at least I did not manage to. same go to svg as well ) I will try again with some research.

**Comment by theanuradha** [comment]
@IanMayo maybe I will try to create PDF base on it in temp location and copy that tempfile to clipboard.

**Comment by theanuradha** [comment]
image

@IanMayo Ok I mange to change code and get WMF/PDF/VECTOR paste on Mac /Linux as well. (used **PDFGraphics2D**) please test on linux for me .

**Comment by theanuradha** [comment]
@IanMayo Just fix page size as well. it now even paste on Browser (eg:Gmail)

image

**Comment by IanMayo** [comment]
No, I don't get paste in Linux.  I get a confirmation that the WMF copy is complete, but then nothing on the clipboard.  Well, I do think there's something on the ClipBoard, but my LibreOffice apps don't understand it.

Maybe now is the time for you to build that Ubuntu VM :-D

**Comment by theanuradha** [comment]
@IanMayo I will setup it over weekend.

**Comment by IanMayo** [comment]
I've installed InkScape on Ubuntu (it's a vector editor).  When I try to paste WMF I get this:

```
org.eclipse.swt.SWTException: Invalid thread access
    at org.eclipse.swt.SWT.error(SWT.java:4361)
    at org.eclipse.swt.SWT.error(SWT.java:4276)
    at org.eclipse.swt.SWT.error(SWT.java:4247)
    at org.eclipse.swt.widgets.Widget.error(Widget.java:480)
    at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:418)
    at org.eclipse.swt.widgets.Control.getBounds(Control.java:738)
    at info.limpet.stackedcharts.ui.view.StackedChartsView$WMFTransfer.getTransferData(StackedChartsView.java:965)
    at sun.awt.datatransfer.DataTransferer.translateTransferable(DataTransferer.java:1180)
    at sun.awt.datatransfer.DataTransferer$6.run(DataTransferer.java:2332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by theanuradha** [comment]
@IanMayo I fix SWT Thread access violations on linux.

**Pull request merged**
