### PR TITLE
update p2  build to bind all 3rd party content

### PR DESCRIPTION
**Pull request by theanuradha**
image

### CODE REVIEW

**Comment by theanuradha** [comment]
@IanMayo  please note: I have format pom.xml

**Comment by IanMayo** [comment]
great, thanks.

**Comment by theanuradha** [comment]
@IanMayo  Just checking https://github.com/debrief/limpet-update/tree/gh-pages/1.0/plugins
Not sure why it not populated with 3rd-party libs yet . did build ran already ?

**Comment by theanuradha** [comment]
When i do local build it correctly generate all dependency

**Comment by theanuradha** [comment]
@IanMayo  Just notice it only upload **report** dir not site. so I need to make sure generated content copy correctly to **report** dir.

**Comment by theanuradha** [comment]
narrow it down to **create_reports.sh** fixing it now

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/305

**Pull request merged**
