### PR TITLE
Issue 265 patched nebula

### PR DESCRIPTION
**Pull request by theanuradha**
@IanMayo  I have build nebula locally with patch and adapt it on our project. 

I had to change Transition direction from LEFT <---> RIGHT to UP <---> DOWN as issues on LEFT/RIGHT MODE

### CODE REVIEW

**Comment by IanMayo** [comment]
thanks for the updated version, but the UP/DOWN transition isn't acceptable - it doesn't meet our UX expectations.

Hopefully Rodrigo will be able to make progress on the LEFT/RIGHT animation

**Comment by theanuradha** [comment]
@IanMayo LEFT/RIGHT he suggest less quality eg: 97%  it works on demo but not in Limpet  so we need proper fix for that.

**Comment by IanMayo** [comment]
@theanuradha - could you explain that a little more, please? Afraid I don't understand.

**Comment by theanuradha** [comment]
@IanMayo 

> Ok...well, if you don't succeed to see the left/right transitions, please try to decrease the transitions quality on the component's demo. I can see the left/right transitions if I decrease the quality to 97%.

this only works on demo. I have try same workaround on Our Chart view and it never work on left/right transitions.

**Comment by IanMayo** [comment]
@theanuradha - there are a couple of new updates from Rodrigo, to address a Linux issue:
https://github.com/cantupolo/nebula/commits/stw-macosx-fix/widgets/effects/org.eclipse.nebula.effects.stw/src/org/eclipse/nebula/effects/stw

**Comment by theanuradha** [comment]
@IanMayo will apply those and push again

**Comment by theanuradha** [comment]
@IanMayo AFter apply latest , ON limpet , Chart view to Editor transition is not correctly rendered . will try on windows little later as issue I did not push yet

**Comment by theanuradha** [comment]
@IanMayo  Windows it works fine, But mac it seems affected. and rendering not correct at all. do u want me to push so u can check on linux ?

**Comment by theanuradha** [comment]
@IanMayo  I have added workaround for Mac issue and all works fine (MAC & WIN). Please check on linux

**Comment by IanMayo** [comment]
Linux isn't very pretty.  We get the first-frame flicker still.  Also, during the transition, the "out-going" is just visible, but the "incoming" image is plain white rectangle.

**Comment by theanuradha** [comment]
I had same issue on Mac  will try workaround fix I did for Mac

**Comment by theanuradha** [comment]
@IanMayo  can you try again with latest , it should fix the empty panel

**Comment by IanMayo** [comment]
Blank panel fixed - thanks. Still have first frame flicker:  we briefly display the target panel, then switch back to the current panel, then rotate happens.

**Comment by theanuradha** [comment]
@IanMayo  I will look on target panel issue, Flick is coming from Nebula code sadly

**Comment by IanMayo** [comment]
```
Flick is coming from Nebula code sadly
```

Oh, so it happens in the Nebula demo app too?

**Comment by theanuradha** [comment]
@IanMayo  Yes

**Comment by IanMayo** [comment]
Hmm, on OSX the flicker image is for the **current** page.  On Linux the flicker image is for the **target** page.   Is that right?

**Comment by theanuradha** [comment]
@IanMayo Yes flicker is gray backgound.

**Comment by IanMayo** [comment]
ok, have created new milestone for Rodrigo that covers the flicker.

**Comment by IanMayo** [comment]
@theanuradha - Rodrigo  ( @cantupolo ) said this:

# 

I submitted the Linux's fix on GitHub, branch stw-linuxflick-fix (https://github.com/cantupolo/nebula/tree/stw-linuxflick-fix).
The fix is about defining a new interface, based on Transitionable interface, where you can implement a method to return the transition image directly to the transition manager, since Linux has problems to get the image from the canvas control.
In your application, instead of implementing Transitionable interface, you'll have to implement ImageTransitionable interface and return the transition image implementing the getControlImage() method. If this method returns null, the original treatment is done, where the TransitionManager will get the image from the canvas control. You can return null if your application is not running on Linux.

Please let me know if you agree with the solution and, if you agree, please make some tests on Linux to verify if there is a flick in the end of the image transition.

Best regards!

Rodrigo

# 

Could you try using his fix?  Note you have to use a new interface to supply the target image.

**Comment by theanuradha** [comment]
@IanMayo  I tested new stw-linuxflick-fix  branch . On mac it dose not even work on Examples sorry. Maybe it works on linux now it break mac

**Comment by IanMayo** [comment]
@theanuradha  - let's talk in Hangouts

**Comment by IanMayo** [comment]
PR closed in error.  PR now still alive here: https://github.com/debrief/limpet/pull/372

**Pull request merged**
